set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

# Specify the cross compiler
set(CMAKE_C_COMPILER ${CMAKE_C_COMPILER} CACHE STRING "" FORCE)
set(CMAKE_CXX_COMPILER ${CMAKE_CXX_COMPILER} CACHE STRING "" FORCE)

# Set the toolchain path
set(TOOLCHAIN_PATH "$ENV{TOOLCHAIN_PATH}")
set(CMAKE_C_COMPILER "${TOOLCHAIN_PATH}/bin/aarch64-openwrt-linux-gcc")
set(CMAKE_CXX_COMPILER "${TOOLCHAIN_PATH}/bin/aarch64-openwrt-linux-g++")
set(CMAKE_SYSROOT "$ENV{STAGING_DIR}/target-aarch64_cortex-a53_musl")
set(CMAKE_FIND_ROOT_PATH "$ENV{STAGING_DIR}/target-aarch64_cortex-a53_musl")

# Search paths
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
